name: Check Grades

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Grade Checker
        env:
          UBS_USERNAME: ${{ secrets.UBS_USERNAME }}
          UBS_PASSWORD: ${{ secrets.UBS_PASSWORD }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python main.py

      - name: Save new grades data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "database is up to date" && git push)
